// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsSite.Models;

namespace NewsSite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200804081904_SeedArticlesTable")]
    partial class SeedArticlesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewsSite.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new { Id = 1, Author = "Henk Smits", Content = "Local bank gave away all its money. Big software bug was probably the cause of it! Very sad...", Title = "Big mistake at local bank" },
                        new { Id = 2, Author = "Maya Bee", Content = "The nature club located in Someren has planted over a thousand flowers in Vendoven Central park. Locals say that it looks beautiful. ", Title = "Flower power" },
                        new { Id = 3, Author = "Cindy Smave", Content = "Tesla is going to announce their new truck in the upcoming weeks. It should be one of the most powerful trucks yet in existence!", Title = "New Tesla Truck" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
